spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ketabcheh
    username: postgres
    password: 123321123

jwt:
  secret: thisismyscretkeyforencodinganddecodingjwttoken
  expiration: 86400000