spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ketabcheh
    username: postgres
    password: 123321123
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

jwt:
  secret: thisismyscretkeyforencodinganddecodingjwttoken
  expiration: 86400000